# Generated by Django 6.0.1 on 2026-01-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora_inicio', 'estacion']},
        ),
        migrations.AddField(
            model_name='turno',
            name='estacion',
            field=models.IntegerField(default=1),
        ),
    ]
