# Generated by Django 6.0.1 on 2026-01-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_turno_options_turno_estacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(default='08:00')),
                ('hora_fin', models.TimeField(default='17:00')),
                ('duracion_turno', models.IntegerField(default=30)),
                ('hora_almuerzo', models.TimeField(default='12:00')),
                ('duracion_almuerzo', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Configuración de Cronograma',
                'verbose_name_plural': 'Configuraciones de Cronograma',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.responsable')),
            ],
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
