# Generated by Django 6.0.1 on 2026-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracioncronograma_feriado_alter_turno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncronograma',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracioncronograma',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
