# Generated by Django 6.0.1 on 2026-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracioncronograma_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
