# Generated by Django 6.0.1 on 2026-01-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipo_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncronograma',
            name='excluir_fines_semana',
            field=models.BooleanField(default=True),
        ),
    ]
