# Generated by Django 6.0.1 on 2026-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracioncronograma_excluir_fines_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
