# Generated by Django 6.0.1 on 2026-01-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_turno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncronograma',
            name='excluir_fines_semana',
        ),
        migrations.AddField(
            model_name='configuracioncronograma',
            name='modo_exclusion',
            field=models.CharField(choices=[('none', 'No excluir'), ('sundays', 'Solo Domingos'), ('weekends', 'Sábados y Domingos')], default='weekends', max_length=20),
        ),
    ]
