# Generated by Django 6.0.1 on 2026-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_configuracioncronograma_excluir_fines_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='notificar_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
