# Generated by Django 6.0.1 on 2026-01-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_turno_notificacion_enviada_turno_notificar_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='turno',
            name='ultimo_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Envío'),
        ),
    ]
