# Generated by Django 6.0.1 on 2026-02-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_responsable_email_turno_ultimo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.responsable'),
        ),
    ]
