# Generated by Django 6.0.1 on 2026-02-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_turno_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.turno'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.responsable'),
        ),
    ]
