# Generated by Django 6.0.1 on 2026-02-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_equipo_turno_alter_equipo_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='notificacion_error',
            field=models.BooleanField(default=False),
        ),
    ]
