# Generated by Django 6.0.1 on 2026-01-29 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_responsable_email_turno_ultimo_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_anticipado', models.BooleanField(default=True, verbose_name='Activar Recordatorio Anticipado')),
                ('dias_antes', models.PositiveIntegerField(default=1, verbose_name='Días de anticipación')),
                ('activar_jornada', models.BooleanField(default=False, verbose_name='Activar Inicio de Jornada')),
                ('hora_inicio_jornada', models.TimeField(default='08:00', verbose_name='Hora Inicio Jornada')),
                ('estados_permitidos', models.JSONField(default=list, verbose_name='Condiciones de Disparo (Estados)')),
                ('asunto_template', models.CharField(default='Recordatorio: {evento} - {fecha}', max_length=255, verbose_name='Plantilla de Asunto')),
                ('cc_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Copia Oculta (CC)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anticipado', 'Recordatorio Anticipado'), ('jornada', 'Inicio de Jornada')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado Exitosamente'), ('fallido', 'Falló el Envío')], default='enviado', max_length=20)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('error_log', models.TextField(blank=True)),
                ('token_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('ip_confirmacion', models.GenericIPAddressField(blank=True, null=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_notificaciones', to='core.turno')),
            ],
            options={
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['fecha_envio', 'estado'], name='notificatio_fecha_e_1b8d26_idx')],
            },
        ),
    ]
