# Generated by Django 6.0.1 on 2026-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialenvio',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='historialenvio',
            name='fecha_confirmacion',
        ),
        migrations.RemoveField(
            model_name='historialenvio',
            name='ip_confirmacion',
        ),
        migrations.RemoveField(
            model_name='historialenvio',
            name='token_confirmacion',
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='cuerpo_template',
            field=models.TextField(default='Hola {funcionario},\n\nTienes una actividad técnica programada:\n\nEvento: {evento}\nFecha: {fecha}\nHora: {hora}\n\nPor favor, asegúrate de estar preparado.', verbose_name='Plantilla de Cuerpo'),
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='cuerpo',
            field=models.TextField(blank=True),
        ),
    ]
