# Generated by Django 6.0.1 on 2026-01-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_historialenvio_confirmado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='estados_permitidos',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='hora_inicio_jornada',
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='minutos_antes_jornada',
            field=models.PositiveIntegerField(default=60, verbose_name='Minutos antes del turno'),
        ),
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='activar_jornada',
            field=models.BooleanField(default=True, verbose_name='Activar Recordatorio el Día del Turno'),
        ),
    ]
