# Generated by Django 6.0.1 on 2026-01-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_configuracionnotificacion_estados_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='actividad_general',
            field=models.CharField(default='Mantenimiento Preventivo', max_length=100, verbose_name='Actividad por Defecto'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='asunto_inicio',
            field=models.CharField(default='Inicio de Cronograma: Mantenimiento Preventivo', max_length=255, verbose_name='Asunto Notificación Inicio'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='cuerpo_inicio',
            field=models.TextField(default='Estimados funcionarios,\n\nSe ha generado el nuevo cronograma de mantenimiento. A partir de ahora recibirán notificaciones automáticas 1 hora antes de sus turnos asignados.\n\nSaludos,\nGestión de Activos.', verbose_name='Cuerpo Notificación Inicio'),
        ),
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Copia Oculta (BCC)'),
        ),
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='cuerpo_template',
            field=models.TextField(default='Hola {funcionario},\n\nTienes una actividad programada:\n\nEvento: {evento}\nFecha: {fecha}\nHora: {hora}\n\nPor favor, asegúrate de estar preparado.', verbose_name='Plantilla de Cuerpo'),
        ),
    ]
