# Generated by Django 6.0.1 on 2026-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_configuracionnotificacion_actividad_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialenvio',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado Exitosamente'), ('fallido', 'Falló el Envío'), ('cancelado', 'Cancelado Manualmente')], default='enviado', max_length=20),
        ),
    ]
