# Generated by Django 6.0.1 on 2026-01-29 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_responsable_email_turno_ultimo_envio'),
        ('notifications', '0005_alter_historialenvio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=255)),
                ('detalles', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEncolada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('anticipado', 'Recordatorio Anticipado'), ('jornada', 'Inicio de Jornada'), ('inicio', 'Broadcast de Inicio')], max_length=20)),
                ('fecha_programada', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'En Procesamiento'), ('enviado', 'Enviado con Éxito'), ('error_temporal', 'Error Temporal (Reintentará)'), ('fallido', 'Fallido (Sin más reintentos)'), ('cancelado', 'Cancelado Manualmente')], db_index=True, default='pendiente', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('ultimo_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notificación Encolada',
                'verbose_name_plural': 'Notificaciones Encoladas',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.RemoveIndex(
            model_name='historialenvio',
            name='notificatio_fecha_e_1b8d26_idx',
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='intento_n',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialenvio',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='notificacionencolada',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cola_notificaciones', to='core.turno'),
        ),
        migrations.AddField(
            model_name='auditlognotificaciones',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='notifications.notificacionencolada'),
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_envio', to='notifications.notificacionencolada'),
        ),
    ]
