# Generated by Django 6.0.1 on 2026-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auditlognotificaciones_notificacionencolada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='asunto_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracionnotificacion',
            name='cuerpo_inicio',
        ),
        migrations.AlterField(
            model_name='notificacionencolada',
            name='tipo',
            field=models.CharField(choices=[('anticipado', 'Recordatorio Anticipado'), ('jornada', 'Recordatorio del Día')], max_length=20),
        ),
    ]
