# Generated by Django 6.0.1 on 2026-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_configuracionnotificacion_asunto_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='asunto_template',
            field=models.CharField(default='Recordatorio: Mantenimiento Preventivo de Hardware ({marca})', max_length=255, verbose_name='Plantilla de Asunto'),
        ),
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='cuerpo_template',
            field=models.TextField(default='Se informa que se realizará el mantenimiento preventivo de los siguientes equipos asignados a su cargo:\n\n{equipos_lista}\n\nDicha actividad se llevará a cabo el día {fecha_turno}, en las oficinas del área de Gestión de Mantenimiento, ubicadas en el Bloque C, planta alta. El horario de atención para su turno específico inicia a las {hora}, con una duración estimada de {duracion} minutos por equipo. Las actividades programadas a ejecutar son las siguientes:\n\n• Limpieza externa e interna: Eliminación de polvo y residuos de componentes internos y carcasa exterior del equipo.\n• Cambio de pasta térmica: Reemplazo de pasta térmica en procesador y componentes críticos para optimizar la transferencia de calor.\n• Diagnóstico de rendimiento: Evaluación integral del funcionamiento del sistema y verificación de parámetros operativos.\n• Actualización de software: Instalación de las últimas versiones de software y parches de seguridad disponibles.\n\nSe solicita coordinar previamente la entrega de sus equipos para garantizar el cumplimiento del cronograma establecido y evitar interrupciones en el servicio durante el período mencionado.', verbose_name='Plantilla de Cuerpo'),
        ),
    ]
