# Generated by Django 6.0.1 on 2026-02-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_configuracionnotificacion_asunto_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlognotificaciones',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='notifications.notificacionencolada'),
        ),
    ]
